using Newtonsoft.Json;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Resources;
using System.Text;

namespace AutoGenerate {
    internal class Program {
        static void Main(string[] args) {

            string loc = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            loc = Path.GetFullPath(Path.Combine(loc, "../../.."));

            string localeJson = File.ReadAllText(Path.Combine(loc, "Amethyst-Installer","Resources","Lang","en.json"));

            var localeDict = JsonConvert.DeserializeObject<Dictionary<string, string>>(localeJson);

            StringBuilder autoGeneratedBuffer = new StringBuilder();
            autoGeneratedBuffer.AppendLine("namespace amethyst_installer_gui {\r\n    /// <summary>\r\n    /// A collection of getters so that I can use the JSON i18n system in XAML\r\n    /// </summary>\r\n    public static class Localisation {\r\n");

            foreach(var key in localeDict.Keys) {
                autoGeneratedBuffer.AppendLine($"        public static string {key} {{\r\n            get {{\r\n                return LocaleManager.GetString(\"{key}\");\r\n            }}\r\n        }}");
            }

            autoGeneratedBuffer.AppendLine("    }\r\n}");

            string finalFile = autoGeneratedBuffer.ToString();
            File.WriteAllText(Path.Combine(loc, "Amethyst-Installer", "Util", "Localisation", "Localisation.cs"), finalFile);
        }
    }
}
