//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amethyst_installer_gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("amethyst_installer_gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Installer_Action_Next {
            get {
                return ResourceManager.GetString("Installer_Action_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install completed.
        /// </summary>
        public static string Sidebar_Task_Done {
            get {
                return ResourceManager.GetString("Sidebar_Task_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Sidebar_Task_Download {
            get {
                return ResourceManager.GetString("Sidebar_Task_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string Sidebar_Task_Install {
            get {
                return ResourceManager.GetString("Sidebar_Task_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to install.
        /// </summary>
        public static string Sidebar_Task_InstallOptions {
            get {
                return ResourceManager.GetString("Sidebar_Task_InstallOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose destination.
        /// </summary>
        public static string Sidebar_Task_Location {
            get {
                return ResourceManager.GetString("Sidebar_Task_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System requirements.
        /// </summary>
        public static string Sidebar_Task_Sysreq {
            get {
                return ResourceManager.GetString("Sidebar_Task_Sysreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Sidebar_Task_Welcome {
            get {
                return ResourceManager.GetString("Sidebar_Task_Welcome", resourceCulture);
            }
        }
    }
}
