//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amethyst_installer_gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("amethyst_installer_gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree.
        /// </summary>
        public static string EULA_Agree {
            get {
                return ResourceManager.GetString("EULA_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do not agree.
        /// </summary>
        public static string EULA_DontAgree {
            get {
                return ResourceManager.GetString("EULA_DontAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Installer_Action_Back {
            get {
                return ResourceManager.GetString("Installer_Action_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy error.
        /// </summary>
        public static string Installer_Action_CopyError {
            get {
                return ResourceManager.GetString("Installer_Action_CopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get help on Discord.
        /// </summary>
        public static string Installer_Action_Discord {
            get {
                return ResourceManager.GetString("Installer_Action_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Installer_Action_Exit {
            get {
                return ResourceManager.GetString("Installer_Action_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Installer_Action_Next {
            get {
                return ResourceManager.GetString("Installer_Action_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log file is stored here:.
        /// </summary>
        public static string Logs_DirectoryIsLocatedHere {
            get {
                return ResourceManager.GetString("Logs_DirectoryIsLocatedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install completed.
        /// </summary>
        public static string Page_Done_Title {
            get {
                return ResourceManager.GetString("Page_Done_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Page_Download_Title {
            get {
                return ResourceManager.GetString("Page_Download_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened.
        /// </summary>
        public static string Page_Exception_Title {
            get {
                return ResourceManager.GetString("Page_Exception_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string Page_Install_Title {
            get {
                return ResourceManager.GetString("Page_Install_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to install.
        /// </summary>
        public static string Page_InstallOptions_Title {
            get {
                return ResourceManager.GetString("Page_InstallOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose destination.
        /// </summary>
        public static string Page_Location_Title {
            get {
                return ResourceManager.GetString("Page_Location_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Page_Logs_Title {
            get {
                return ResourceManager.GetString("Page_Logs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System requirements.
        /// </summary>
        public static string Page_Sysreq_Title {
            get {
                return ResourceManager.GetString("Page_Sysreq_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install completed.
        /// </summary>
        public static string Sidebar_Task_Done {
            get {
                return ResourceManager.GetString("Sidebar_Task_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Sidebar_Task_Download {
            get {
                return ResourceManager.GetString("Sidebar_Task_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string Sidebar_Task_Install {
            get {
                return ResourceManager.GetString("Sidebar_Task_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to install.
        /// </summary>
        public static string Sidebar_Task_InstallOptions {
            get {
                return ResourceManager.GetString("Sidebar_Task_InstallOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose destination.
        /// </summary>
        public static string Sidebar_Task_Location {
            get {
                return ResourceManager.GetString("Sidebar_Task_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System requirements.
        /// </summary>
        public static string Sidebar_Task_Sysreq {
            get {
                return ResourceManager.GetString("Sidebar_Task_Sysreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Sidebar_Task_Welcome {
            get {
                return ResourceManager.GetString("Sidebar_Task_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View logs.
        /// </summary>
        public static string Sidebar_ViewLogs {
            get {
                return ResourceManager.GetString("Sidebar_ViewLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible devices.
        /// </summary>
        public static string SystemRequirement_Category_Compatibility {
            get {
                return ResourceManager.GetString("SystemRequirement_Category_Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk space.
        /// </summary>
        public static string SystemRequirement_Category_Storage {
            get {
                return ResourceManager.GetString("SystemRequirement_Category_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB controllers.
        /// </summary>
        public static string SystemRequirement_Category_UsbControllers {
            get {
                return ResourceManager.GetString("SystemRequirement_Category_UsbControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VR headset.
        /// </summary>
        public static string SystemRequirement_Category_VrSystem {
            get {
                return ResourceManager.GetString("SystemRequirement_Category_VrSystem", resourceCulture);
            }
        }
    }
}
